### ISSUE TITLE
Azure documentation is unclear

### ISSUE THREAD

**Issue by cerdmann-pivotal** [pivotal-cf/docs-addon-ipsec#18]
This line is unclear: https://github.com/pivotal-cf/docs-addon-ipsec/blob/a641dbef41cf2ea5995b475ab9eeb0687435f90d/installing.html.md.erb#L70

Which protocol on ports 50 and 51. Is it all protocols?

**Comment by animatedmax** [comment]
Hi @cerdmann-pivotal We updated the http://docs.pivotal.io/addon-ipsec/installing.html topic to clarify the protocols and ports. Thanks!
